### ISSUE TITLE
TypeError: Cannot read property 'error' of undefined when authenticating

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-did#26] opened 2021-03-16 15:14 UTC
I have some code that looks like:

```ts
const threeID = await ThreeID.create({
      authId: "genesis",
      authSecret,
      getPermission: () => Promise.resolve([]),
      // @ts-expect-error
      ceramic,
    });
    const provider = threeID.getDidProvider();
    await ceramic.setDIDProvider(provider);
    const resolver = ThreeIDResolver.getResolver(ceramic);
    const did = new DID({ provider, resolver });
   // throws error
    await did.authenticate();
```

```js
    {
      err: TypeError: Cannot read property 'error' of undefined
          at DID.<anonymous> (/Users/jonathanschwartz/Documents/daemon-land/pdm/node_modules/dids/src/index.ts:300:38)
          at Generator.next (<anonymous>)
          at fulfilled (/Users/jonathanschwartz/Documents/daemon-land/pdm/node_modules/dids/lib/index.js:5:58)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
    }
```

`"@ceramicnetwork/3id-did-resolver@0.6.10"`
`"@ceramicnetwork/http-client@0.9.6"`
`3id-did-provider@0.5.1`

**Comment by oed** [comment] 2021-03-21 08:52
What version of `dids` are you using? Looks like this is an error caused by using v2. Try downgrading maybe?

**Comment by Entryist** [comment] 2021-03-21 13:59
I encountered the same error doing the Ceramic tutorial [How to store signed and encrypted data on IPFS](https://blog.ceramic.network/how-to-store-signed-and-encrypted-data-on-ipfs/). 

Downgrading js-dids to ^1.0.0 worked for me.

**Comment by oed** [comment] 2021-03-21 14:14
Glad to hear @Entryist This will be fixed once the new version of Ceramic is released within the next few days.

**Comment by iamhappymonk** [comment] 2021-07-10 07:50
@oed still facing the issue while running ^2.1.0 , is this fixed?

**Comment by oed** [comment] 2021-07-10 10:17
This issue should actually be fixed. Can you share what you are doing exactly @iamhappymonk ?

**Comment by iamhappymonk** [comment] 2021-07-14 01:43
Hey! Apologies for the late reply.  Following is the piece of code. 

`                        const mn = randomBytes(32)
			const provider = new Ed25519Provider(mn);
			const did = new DID({ provider: provider, resolver: KeyResolver.getResolver() });
			console.log('Authenticating', did.id);
			await did.authenticate();`

I was able to fix this by forking and updating the error section in the did. Tried Downgrading and other bits. Doesn't help. There is a forked version with the tiny update.
The code works successfully on react-native 
Breaks when running on nodejs. After fix i land into the following error.
Though that lands up to issue of on the server-side when I try and generate another did at the backend

> Error: invalid_signature: Signature invalid for JWT
>     at verifyEd25519 (/Users/iamhappymonk/chokidr/microservices/node_modules/did-jwt/src/VerifierAlgorithm.ts:134:22)
>     at verifyJWSDecoded (/Users/iamhappymonk/chokidr/microservices/node_modules/did-jwt/src/JWT.ts:262:38)
>     at Object.verifyJWS (/Users/iamhappymonk/chokidr/microservices/node_modules/did-jwt/src/JWT.ts:279:10)
>     at DID.<anonymous> (/Users/iamhappymonk/chokidr/microservices/node_modules/dids/src/did.ts:241:3)
>     at Generator.next (<anonymous>)
>     at fulfilled (/Users/iamhappymonk/chokidr/microservices/node_modules/dids/lib/did.js:5:58)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

What seems to be the issue?

**Comment by oed** [comment] 2021-07-14 08:16
That's strange! Have not seen this error elsewhere. 

> I was able to fix this by forking and updating the error section in the did

What was the change you made? Maybe you could make a PR?

@ukstv if you have a minute could you have a look at @iamhappymonk's issue and see if you can replicate?

**Comment by iamhappymonk** [comment] 2021-07-15 02:16
Absolutely. I will create a PR in a few days for the same.

**Comment by ukstv** [comment] 2021-07-20 13:50
The first issue by @Schwartz10: version mismatch between `dids` package and the `3id-did-resolver`. The latter one you used is old, and incompatible with the newer `dids` you used, hence the error. Technically speaking, old 3id-did-resolver returned DID Document, while new one returns did resolution result, which is expected by the newer `dids`.

I guess the same is true for other people.

Please, use the latest packages.

@iamhappymonk I created gist that, as far as I can, mimics what you are trying to achieve: https://gist.github.com/ukstv/47abf53c15d1399bde65d6b8dd8ebbf5 Works all right. One thing here: you can only know `did.id` after you do `await did.authenticate()`, hence slightly changed order of lines if compared to your snippet.

**Comment by ukstv** [comment] 2021-07-20 13:51
Please, @iamhappymonk tell here if you see any errors after you update the packages.

**Comment by Geo25rey** [comment] 2021-07-21 20:17
@ukstv We at DNS are facing a similar issue, but we have updated all our packages fairly recently and once a DID reaches the invalid JWT error it can't be recovered. We have the authId and authSecret available if needed.

**Closed** 2022-01-12 15:56 UTC
Labels: bug, p3
